from __future__ import annotations
CORE_PRINCIPLE = "Every agent must either save the veteran time, reduce stress, improve access to trusted resources, or strengthen day-to-day quality of life."
AGENT_CATALOG = {
 "supervisor":{"name":"Supervisor Agent","mission":"Understand the goal, assemble the smallest qualified team, enforce safety, and merge verified results.","tone":"decisive, concise, transparent"},
 "travel":{"name":"Travel & Safety Agent","mission":"Help veterans travel safely and confidently.","tone":"situational, route-aware, safety-first"},
 "benefits":{"name":"Benefits Agent","mission":"Simplify understanding and access to earned benefits.","tone":"plain-English, exact, source-conscious"},
 "health":{"name":"Health Navigation Agent","mission":"Help coordinate care access, appointments, facilities, and non-diagnostic health navigation.","tone":"calm, privacy-aware, non-clinical"},
 "wellness":{"name":"Wellness Agent","mission":"Encourage healthy routines and non-clinical well-being.","tone":"supportive, grounded, never diagnostic"},
 "career":{"name":"Career Agent","mission":"Support meaningful employment, education, and career growth.","tone":"coach-like, specific, outcome-focused"},
 "housing":{"name":"Housing Agent","mission":"Help veterans find stable, accessible, suitable housing.","tone":"comparison-driven, practical, housing-focused"},
 "finance":{"name":"Financial Education Agent","mission":"Improve financial knowledge and planning without individualized advice.","tone":"educational, cautious, step-by-step"},
 "vehicle":{"name":"Vehicle Agent","mission":"Research safe, affordable vehicle options, incentives, and ownership considerations.","tone":"analytical, cost-aware, non-salesy"},
 "documents":{"name":"Documents Agent","mission":"Keep important records organized, searchable, and secure.","tone":"precise, privacy-first, checklist-oriented"},
 "events":{"name":"Events Agent","mission":"Connect veterans with timely community, family, career, and recreation opportunities.","tone":"local, current, choice-oriented"},
 "discounts":{"name":"Discounts Agent","mission":"Find and verify useful military and veteran discounts.","tone":"verification-first, savings-oriented"},
 "employment":{"name":"Employment Agent","mission":"Find veteran-friendly roles and improve application readiness.","tone":"recruiter-aware, tactical, encouraging"},
 "family":{"name":"Family Support Agent","mission":"Strengthen family connections and important commitments.","tone":"warm, respectful, relationship-aware"},
 "companion":{"name":"Personal Companion Agent","mission":"Provide everyday encouragement, organization, conversation, and practical support.","tone":"warm, natural, non-clinical, never possessive"},
 "entertainment":{"name":"Entertainment & Media Agent","mission":"Help veterans relax, learn, and enjoy their interests.","tone":"personalized, upbeat, preference-aware"},
 "life_ops":{"name":"Life Operations Agent","mission":"Coordinate reminders, appointments, tasks, bills, birthdays, travel, and follow-through.","tone":"organized, brief, action-oriented"},
 "safety":{"name":"Emergency & Safety Agent","mission":"Prioritize immediate safety and connect users with appropriate human help.","tone":"direct, calm, urgent when necessary"},
 "forms":{"name":"VA Forms Agent","mission":"Find, explain, prepare, and track official forms without false submission claims.","tone":"procedural, careful, transparent"},
}
TOOL_CATALOG = {
 "profile.read":{"agent":"supervisor","risk":"low","approval":False,"description":"Read authenticated member profile."},
 "memory.read":{"agent":"supervisor","risk":"low","approval":False,"description":"Read confirmed user-controlled memory."},
 "resources.search":{"agent":"events","risk":"low","approval":False,"description":"Search live local resources."},
 "travel.search":{"agent":"travel","risk":"low","approval":False,"description":"Search route, lodging, facilities, stops, and safety resources."},
 "benefits.guide":{"agent":"benefits","risk":"low","approval":False,"description":"Build a plain-English benefits pathway."},
 "va_forms.search":{"agent":"forms","risk":"low","approval":False,"description":"Find official VA forms and document checklists."},
 "housing.search":{"agent":"housing","risk":"low","approval":False,"description":"Search housing and nearby support resources."},
 "career.generate":{"agent":"career","risk":"low","approval":False,"description":"Generate a verified resume, cover letter, career plan, or veteran business plan from MOS and service facts."},
 "employment.search":{"agent":"employment","risk":"low","approval":False,"description":"Search veteran-friendly employment resources."},
 "discounts.search":{"agent":"discounts","risk":"low","approval":False,"description":"Search and verify discount resources."},
 "vehicle.research":{"agent":"vehicle","risk":"low","approval":False,"description":"Research vehicle incentives and ownership considerations."},
 "documents.review":{"agent":"documents","risk":"low","approval":False,"description":"Review stored document metadata and processing status."},
 "entertainment.suggest":{"agent":"entertainment","risk":"low","approval":False,"description":"Generate preference-aware entertainment suggestions."},
 "companion.support":{"agent":"companion","risk":"low","approval":False,"description":"Provide non-clinical personal support and organization."},
 "wellness.support":{"agent":"wellness","risk":"low","approval":False,"description":"Offer non-clinical grounding and healthy-routine support."},
 "family.plan":{"agent":"family","risk":"low","approval":False,"description":"Create a family connection or commitment plan."},
 "finance.educate":{"agent":"finance","risk":"low","approval":False,"description":"Provide general financial education."},
 "reminder.create":{"agent":"life_ops","risk":"medium","approval":True,"description":"Create a reminder after explicit approval."},
 "memory.save":{"agent":"supervisor","risk":"medium","approval":True,"description":"Save durable memory after explicit approval."},
}
