import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Shield,Mic,MicOff,LogOut,User,Calendar,MapPin,Heart,Folder,Music,Bell,Brain,Search,ChevronRight,BarChart3,Lock,Eye,EyeOff,Plus,Upload,FileText,RefreshCw,Radio}from'lucide-react';
import'./style.css';
import valorLogo from './assets/valorbuddy-logo.png';
import armyEmblem from './assets/branches/army.png';
import navyEmblem from './assets/branches/navy.png';
import airForceEmblem from './assets/branches/airforce.png';
import marinesEmblem from './assets/branches/marines.png';
import coastGuardEmblem from './assets/branches/coastguard.png';
import spaceForceEmblem from './assets/branches/spaceforce.png';
import{captureDeviceLocation,scheduleLocalReminder}from'./native';
const API=(import.meta.env.VITE_API_BASE_URL||'https://valorbuddy.onrender.com').replace(/\/$/,'');
const branches={
Army:{cls:'army',emblem:armyEmblem,label:'Army Mission Control',motto:'Duty. Honor. Support.',style:{'--bg':'#06140b','--panel':'#0b2111','--panel2':'#102f18','--accent':'#75f06e','--accent2':'#e6c96a','--text':'#fff5cf','--muted':'#c7d8b1','--border':'#4caf50'}},
Navy:{cls:'navy',emblem:navyEmblem,label:'Navy Fleet Command',motto:'Honor. Courage. Commitment.',style:{'--bg':'#061a33','--panel':'#08244a','--panel2':'#0b3568','--accent':'#ffffff','--accent2':'#ffffff','--text':'#ffffff','--muted':'#d8e7ff','--border':'#ffffff'}},
'Air Force':{cls:'airforce',emblem:airForceEmblem,label:'Air Force Flight Operations',motto:'Aim High. Fly. Fight. Support.',style:{'--bg':'#071a2f','--panel':'#0d2d52','--panel2':'#123f73','--accent':'#c9ced6','--accent2':'#d6d9df','--text':'#e6e8ec','--muted':'#b9c0ca','--border':'#8b95a3'}},
Marines:{cls:'marines',emblem:marinesEmblem,label:'Marine Command Post',motto:'Semper Fidelis. Always Faithful.',style:{'--bg':'#1f120b','--panel':'#332014','--panel2':'#4b2b18','--accent':'#ff3131','--accent2':'#ff3131','--text':'#ffd9d0','--muted':'#e5b9a8','--border':'#c92b2b'}},
'Coast Guard':{cls:'coastguard',emblem:coastGuardEmblem,label:'Coast Guard Rescue Operations',motto:'Semper Paratus. Always Ready.',style:{'--bg':'#031922','--panel':'#062838','--panel2':'#0d3d54','--accent':'#36d7ff','--accent2':'#ff7a1a','--text':'#effcff','--muted':'#b9dce7','--border':'#12a4c8'}},
'Space Force':{cls:'spaceforce',emblem:spaceForceEmblem,label:'Space Force Orbital Command',motto:'Semper Supra. Always Above.',style:{'--bg':'#070716','--panel':'#11112d','--panel2':'#1c1b45','--accent':'#b794ff','--accent2':'#d8d8ff','--text':'#f5f2ff','--muted':'#c8c1ef','--border':'#7c4dff'}}
};
const branchAliases={
  army:'Army','u.s. army':'Army','us army':'Army','army veteran':'Army','u.s. army veteran':'Army',
  navy:'Navy','u.s. navy':'Navy','us navy':'Navy','navy veteran':'Navy','u.s. navy veteran':'Navy',
  airforce:'Air Force','air force':'Air Force','u.s. air force':'Air Force','us air force':'Air Force','air force veteran':'Air Force','u.s. air force veteran':'Air Force',
  marines:'Marines','marine':'Marines','marine corps':'Marines','u.s. marine corps':'Marines','us marine corps':'Marines','marines veteran':'Marines','marine corps veteran':'Marines',
  coastguard:'Coast Guard','coast guard':'Coast Guard','u.s. coast guard':'Coast Guard','us coast guard':'Coast Guard','coast guard veteran':'Coast Guard',
  spaceforce:'Space Force','space force':'Space Force','u.s. space force':'Space Force','us space force':'Space Force','space force veteran':'Space Force'
};
function normalizeBranch(value){
  const raw=String(value||'').trim();
  if(branches[raw]) return raw;
  const key=raw.toLowerCase().replace(/[^a-z\s.]/g,'').replace(/\s+/g,' ').trim();
  return branchAliases[key]||branchAliases[key.replace(/\./g,'')]||'Army';
}
function applyBranchTheme(branch){
  const key=normalizeBranch(branch);
  const b=branches[key]||branches.Army;
  try{
    document.documentElement.setAttribute('data-branch',b.cls);
    document.body.setAttribute('data-branch',b.cls);
    document.body.classList.remove('army','navy','airforce','marines','coastguard','spaceforce');
    document.body.classList.add(b.cls);
    Object.entries(b.style||{}).forEach(([k,v])=>document.documentElement.style.setProperty(k,v));
    document.documentElement.style.setProperty('--branch-emblem',`url(${b.emblem})`);
    localStorage.setItem('valor_branch_theme',key);
  }catch{}
  return key;
}


function saveBrowserLocation(){
  try{
    if(!navigator.geolocation)return;
    navigator.geolocation.getCurrentPosition(pos=>{
      const lat=pos.coords.latitude;
      const lng=pos.coords.longitude;
      localStorage.setItem('valor_lat',String(lat));
      localStorage.setItem('valor_lng',String(lng));
    },()=>{}, {enableHighAccuracy:true,timeout:8000,maximumAge:300000});
  }catch{}
}
function locationPayload(){
  const lat=localStorage.getItem('valor_lat');
  const lng=localStorage.getItem('valor_lng');
  return {lat:lat?Number(lat):null,lng:lng?Number(lng):null};
}
function authHeaders(){const t=localStorage.getItem('valor_token');return t?{Authorization:`Bearer ${t}`}:{} }
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...authHeaders(),...(opts.headers||{})}});if(!r.ok){let e='Request failed';try{e=(await r.json()).detail||e}catch{}throw new Error(e)}return r.json()}
function speak(text){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.96;u.pitch=.9;speechSynthesis.speak(u)}catch{}}
function App(){useEffect(()=>{captureDeviceLocation()},[]);const[token,setToken]=useState(localStorage.getItem('valor_token'));const[user,setUser]=useState(null);const[screen,setScreen]=useState('dashboard');const[loading,setLoading]=useState(true);const[branchTheme,setBranchTheme]=useState(()=>normalizeBranch(localStorage.getItem('valor_branch_theme')||'Army'));useEffect(()=>{saveBrowserLocation()},[]);useEffect(()=>{applyBranchTheme(branchTheme)},[branchTheme]);useEffect(()=>{if(!token){setLoading(false);return}api('/auth/me').then(u=>{const normalized=normalizeBranch(localStorage.getItem('valor_branch_theme')||u.branch);setUser({...u,branch:normalized});setBranchTheme(normalized)}).catch(()=>{localStorage.removeItem('valor_token');setToken(null)}).finally(()=>setLoading(false))},[token]);if(loading)return <div className="boot"><Shield/>ValorBuddy loading...</div>;if(!token||!user)return <Auth onLogin={(t,u)=>{const normalized=normalizeBranch(u.branch);localStorage.setItem('valor_token',t);applyBranchTheme(normalized);setBranchTheme(normalized);setToken(t);setUser({...u,branch:normalized})}}/>;const safeBranch=normalizeBranch(branchTheme||user.branch);const b=branches[safeBranch]||branches.Army;return <div className={`app ${b.cls}`} data-branch={b.cls} style={b.style}><Sidebar user={{...user,branch:safeBranch}} screen={screen} setScreen={setScreen}/><main><Topbar user={{...user,branch:safeBranch}} b={b} setScreen={setScreen} setUser={setUser} setBranchTheme={setBranchTheme} onLogout={()=>{localStorage.removeItem('valor_token');setToken(null);setUser(null)}}/><GlobalSearch user={{...user,branch:safeBranch}} setScreen={setScreen}/>{screen==='dashboard'&&<Dashboard user={{...user,branch:safeBranch}} setScreen={setScreen}/>} {screen==='companion'&&<Companion user={{...user,branch:safeBranch}}/>} {screen==='events'&&<Events user={{...user,branch:safeBranch}}/>} {screen==='memories'&&<Memories/>} {screen==='reminders'&&<Reminders/>} {screen==='documents'&&<Documents/>} {screen==='benefits'&&<Benefits user={{...user,branch:safeBranch}}/>} {screen==='music'&&<MusicPage user={{...user,branch:safeBranch}}/>} {screen==='admin'&&<Admin/>} {screen==='profile'&&<Profile user={{...user,branch:safeBranch}} setUser={setUser}/>}</main></div>}
function Auth({onLogin}){const[tab,setTab]=useState('login');const[show,setShow]=useState(false);const[err,setErr]=useState('');const[form,setForm]=useState({email:'demo@valorbuddy.com',password:'ValorDemo123!',first_name:'James',last_name:'',branch:'Army',city:'Dallas',state:'TX'});async function submit(e){e.preventDefault();setErr('');try{const endpoint=tab==='login'?'/auth/login':'/auth/register';const d=await api(endpoint,{method:'POST',body:JSON.stringify(form)});onLogin(d.token,d.user)}catch(ex){setErr(ex.message)}}const currentTheme=branches[normalizeBranch(form.branch)]||branches.Army;return <div className={`loginPage ${currentTheme.cls}`} data-branch={currentTheme.cls} style={currentTheme.style}><div className="loginCard"><div className="brand"><img className="authEmblem" src={currentTheme.emblem} alt={`${form.branch} emblem`}/><h1>ValorBuddy</h1><p>Your AI veteran assistant</p>{tab==='register'&&<small>Your selected branch automatically controls your mission-control interface.</small>}</div><div className="tabs"><button className={tab==='login'?'active':''}onClick={()=>setTab('login')}>Login</button><button className={tab==='register'?'active':''}onClick={()=>setTab('register')}>Create Account</button></div><form onSubmit={submit}>{tab==='register'&&<><label>Service Branch<select value={form.branch}onChange={e=>setForm({...form,branch:e.target.value})}>{Object.keys(branches).map(x=><option key={x}>{x}</option>)}</select></label><label>First Name<input value={form.first_name}onChange={e=>setForm({...form,first_name:e.target.value})}/></label><div className="row"><label>City<input value={form.city}onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input value={form.state}onChange={e=>setForm({...form,state:e.target.value})}/></label></div></>}<label>Email<input type="email" value={form.email}onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<div className="password"><input type={show?'text':'password'} value={form.password}onChange={e=>setForm({...form,password:e.target.value})}/><button type="button"onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{err&&<p className="err">{err}</p>}<button className="primary">{tab==='login'?'Enter Mission Control':'Create Account'}</button></form><div className="quick"><b>Test logins</b><button onClick={()=>setForm({...form,email:'demo@valorbuddy.com',password:'ValorDemo123!'})}>Veteran demo</button><button onClick={()=>setForm({...form,email:'admin@valorbuddy.com',password:'ValorAdmin123!'})}>Admin</button></div></div></div>}
function Sidebar({user,screen,setScreen}){const nav=[['dashboard','Dashboard',Shield],['companion','AI Assistant',Brain],['events','Activities',MapPin],['benefits','Benefits',Search],['memories','Memories',Heart],['reminders','Reminders',Bell],['documents','Document Vault',Folder],['music','Music',Music],['profile','Profile',User]];if(user.role==='admin')nav.push(['admin','Admin Dashboard',BarChart3]);return <aside><div className="logo"><div className="logoStack"><img src={valorLogo} alt="ValorBuddy logo"/><img className="branchMini" src={(branches[normalizeBranch(user.branch)]||branches.Army).emblem} alt={`${user.branch} emblem`}/></div><div><b>VALORBUDDY</b><span>Your AI Veteran Assistant</span></div></div><div className="miniProfile"><User/><div><b>{user.first_name}</b><span>{user.branch} Veteran</span><small>{user.city}, {user.state}</small></div></div>{nav.map(([id,label,Icon])=><button className={screen===id?'active':''}key={id}onClick={()=>setScreen(id)}><Icon/>{label}</button>)}<div className="pledge">COMMITMENT<br/><span>Supporting those who served. Always.</span></div></aside>}
function Topbar({user,b,setScreen,setUser,setBranchTheme,onLogout}){async function changeBranch(branch){const normalized=applyBranchTheme(branch);setBranchTheme(normalized);setUser(u=>({...u,branch:normalized}));requestAnimationFrame(()=>applyBranchTheme(normalized));setTimeout(()=>applyBranchTheme(normalized),80);try{await api('/api/profile/branch',{method:'POST',body:JSON.stringify({branch:normalized})})}catch(e){console.warn('Branch theme save failed; keeping local theme for demo',e)}}return <header><div className="commandIdentity"><img src={b.emblem} alt={`${user.branch} emblem`}/><div><b>{b.label}</b><span>{b.motto}</span></div></div><div className="status">// PRIVATE //</div><nav>{Object.keys(branches).map(x=><button type="button" title={`Switch to ${x} theme`} className={normalizeBranch(user.branch)===x?'active':''}key={x}onClick={()=>changeBranch(x)}>{x}</button>)}</nav><button onClick={()=>setScreen('companion')}><Mic/>Voice</button><button onClick={onLogout} className="logout"><LogOut/>Logout</button></header>}
function GlobalSearch({user,setScreen}){const[q,setQ]=useState('');function go(e){e?.preventDefault?.();const v=q.trim().toLowerCase();if(!v)return;if(v.includes('event')||v.includes('activit')||v.includes('place')||v.includes('vfw')||v.includes('coffee'))setScreen('events');else if(v.includes('benefit')||v.includes('va')||v.includes('claim')||v.includes('spouse')||v.includes('dependent'))setScreen('benefits');else if(v.includes('document')||v.includes('dd214')||v.includes('vault'))setScreen('documents');else if(v.includes('remind')||v.includes('appointment'))setScreen('reminders');else if(v.includes('music'))setScreen('music');else setScreen('companion')}return <form className="globalSearch" onSubmit={go}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search benefits, spouse/dependent access, activities near ${user.city}, documents...`}/><button type="submit">Search</button></form>}
function Hero({user}){const b=branches[normalizeBranch(user.branch)]||branches.Army;return <section className="hero" style={{'--hero-emblem':`url(${b.emblem})`}}><img className="heroEmblem" src={b.emblem} alt="" aria-hidden="true"/><div><h1>WELCOME BACK, {user.first_name.toUpperCase()}</h1><b>{user.branch.toUpperCase()} VETERAN</b><p>ValorBuddy helps veterans, spouses, and dependents navigate resources, track missions, organize documents, stay connected, and get practical support.</p></div><VoicePanel user={user}/></section>}
function VoicePanel({user,onResult}){const[listening,setListening]=useState(false);const[transcript,setTranscript]=useState('');const[typed,setTyped]=useState('');const[reply,setReply]=useState('');const[results,setResults]=useState([]);const[grounded,setGrounded]=useState(false);const rec=useRef(null);async function send(text){const q=(text||'').trim();if(!q)return;setTranscript(q);setTyped('');setReply('Checking live sources and your ValorBuddy profile...');setResults([]);try{const d=await api('/api/vapi/action',{method:'POST',body:JSON.stringify({message:q,query:q,first_name:user.first_name,email:user.email,branch:user.branch,city:user.city,state:user.state,user_type:user.user_type||'Veteran',...locationPayload()})});setReply(d.response);setResults(d.data?.items||[]);setGrounded(Boolean(d.data?.grounded||d.data?.live||d.grounded));speak(d.response);onResult?.(d)}catch(e){setReply(e.message)}}function start(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setReply('Speech recognition is not available in this browser. Type your request below or use Chrome/Android.');return}const r=new SR();r.lang='en-US';r.interimResults=true;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setReply('Microphone permission is needed. Allow microphone access, then try again.')} ;r.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;if(e.results[e.results.length-1].isFinal)send(text);else setTranscript(text)};rec.current=r;r.start()}return <div className="voiceBox"><div className="voiceHeading"><h3><Radio/> Intelligent Voice Command</h3><span className={grounded?'liveAware on':'liveAware'}>{grounded?'LIVE SOURCES':'REAL-TIME READY'}</span></div><p>Speak naturally. Ask about current travel safety, weather, nearby VA resources, housing, veteran discounts, jobs, veteran-owned businesses, auto buying, benefits, reminders, or financial education.</p><button className="mic" onClick={()=>listening?rec.current?.stop():start()}>{listening?<MicOff/>:<Mic/>}<span>{listening?'Listening...':'Tap to Speak'}</span></button><div className="voiceComposer"><input value={typed} onChange={e=>setTyped(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send(typed)} placeholder="Or type a real-time question..."/><button onClick={()=>send(typed)}>Ask</button></div>{transcript&&<small>You said: {transcript}</small>}{reply&&<div className="reply">{reply}</div>}{results.length>0&&<div className="voiceResults">{results.slice(0,4).map((x,i)=><a key={i} href={x.maps_url||x.url||'#'} target="_blank" rel="noreferrer" className="miniResult"><b>{x.title}</b><span>{x.location||x.type}</span>{x.rating&&<small>Rating {x.rating}</small>}</a>)}</div>}</div>}
function Dashboard({user,setScreen}){const[brief,setBrief]=useState(null);useEffect(()=>{api('/api/briefing').then(setBrief).catch(()=>{})},[]);return <><Hero user={user}/><div className="quickCards">{[['AI Assistant','Ask anything and get clear next steps.',Brain,'companion'],['Find Activities','Live Google Places veteran-friendly search.',MapPin,'events'],['Document Vault','Upload and search important records.',Folder,'documents'],['Reminders','Track appointments and commitments.',Bell,'reminders'],['Benefits','Plain-English VA benefit guidance for veterans, spouses, and dependents.',Search,'benefits']].map(([t,d,I,s])=><div className="card"onClick={()=>setScreen(s)}key={t}><I/><h3>{t}</h3><p>{d}</p><button>Open <ChevronRight/></button></div>)}</div><section className="glance"><h2>Today’s Briefing</h2><div><b>{brief?.greeting||`Good to see you, ${user.first_name}. How is your day going?`}</b><p>{brief?.wellness_prompt||'Choose one positive action today.'}</p></div><div className="metric"><Bell/> {brief?.reminders?.length||0}<span>Reminders</span></div><div className="metric"><MapPin/> {brief?.events?.length||0}<span>Nearby options</span></div></section></>}
function Companion({user}){const[msg,setMsg]=useState('');const[items,setItems]=useState([{role:'assistant',content:`Good to see you, ${user.first_name}. How is your day going today?`}]);async function send(text=msg){if(!text)return;setItems([...items,{role:'user',content:text}]);setMsg('');const d=await api('/api/companion/chat',{method:'POST',body:JSON.stringify({message:text})});setItems(v=>[...v,{role:'assistant',content:d.response}]);speak(d.response)}return <section className="page"><VoicePanel user={user} onResult={d=>setItems(v=>[...v,{role:'assistant',content:d.response}])}/><div className="chat">{items.map((m,i)=><div className={m.role}key={i}>{m.content}</div>)}<div className="composer"><input value={msg}onChange={e=>setMsg(e.target.value)}onKeyDown={e=>e.key==='Enter'&&send()}placeholder="Ask ValorBuddy..."/><button onClick={()=>send()}>Send</button></div></div></section>}
function Events({user}){const[items,setItems]=useState([]);const[live,setLive]=useState(false);const[query,setQuery]=useState('veteran events VFW American Legion coffee VA clinic parks');async function load(){const loc=locationPayload();const geo=`${loc.lat&&loc.lng?`&lat=${encodeURIComponent(loc.lat)}&lng=${encodeURIComponent(loc.lng)}`:''}`;const d=await api(`/api/events/search?city=${encodeURIComponent(user.city||'')}&state=${encodeURIComponent(user.state||'')}&keyword=${encodeURIComponent(query)}${geo}`);setItems(d.items||[]);setLive(d.live)}useEffect(()=>{load()},[]);return <section className="page"><h1>Veteran-friendly activities <span className="badge">{live?'LIVE GOOGLE':'DEMO MODE'}</span></h1><div className="composer"><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Try: veteran coffee, VFW, parks, VA clinic"/><button className="primary"onClick={load}><RefreshCw/>Search</button></div><Grid items={items}/></section>}
function Benefits({user}){const[q,setQ]=useState('VA benefits for veterans spouses and dependents');const[data,setData]=useState(null);async function search(){setData(await api(`/api/benefits/search?query=${encodeURIComponent(q)}&state=${user.state}&branch=${user.branch}`))}return <section className="page"><h1>Benefits Guidance</h1><div className="composer"><input value={q}onChange={e=>setQ(e.target.value)}/><button onClick={search}>Search</button></div>{data&&<Grid items={data.items.map(x=>({title:x.title,description:x.summary,location:x.next_step}))}/>}<p className="muted">Includes veteran, spouse, survivor, caregiver, and dependent pathways. Informational only; use VA.gov or a VA-accredited representative for official guidance.</p></section>}
function MusicPage({user}){const[m,setM]=useState('calm');const[items,setItems]=useState([]);async function go(){const d=await api(`/api/music/suggest?mood=${m}&branch=${user.branch}`);setItems(d.items||[])}useEffect(()=>{go()},[]);return <section className="page"><h1>Music Companion</h1><div className="composer"><input value={m}onChange={e=>setM(e.target.value)}placeholder="calm, gospel, country, patriotic"/><button onClick={go}>Suggest</button></div><Grid items={items}/></section>}
function Memories(){const[title,setTitle]=useState('');const[note,setNote]=useState('');const[items,setItems]=useState([]);async function load(){setItems(await api('/api/memories'))}useEffect(()=>{load()},[]);async function save(){await api('/api/memories',{method:'POST',body:JSON.stringify({title,note,tags:['positive']})});setTitle('');setNote('');load()}return <section className="page"><h1>Memory Wall</h1><div className="composer"><input value={title}onChange={e=>setTitle(e.target.value)}placeholder="Memory title"/><input value={note}onChange={e=>setNote(e.target.value)}placeholder="Story or note"/><button onClick={save}><Plus/>Save</button></div><Grid items={items}/></section>}
function Reminders(){const[title,setTitle]=useState('');const[when,setWhen]=useState('Tomorrow 10 AM');const[items,setItems]=useState([]);async function load(){setItems(await api('/api/reminders'))}useEffect(()=>{load()},[]);async function save(){await api('/api/reminders',{method:'POST',body:JSON.stringify({title,when_text:when})});const at=new Date(when);if(!Number.isNaN(at.getTime())&&at>Date.now())await scheduleLocalReminder(title,at);setTitle('');load()}return <section className="page"><h1>Reminders</h1><div className="composer"><input value={title}onChange={e=>setTitle(e.target.value)}placeholder="Call the VA"/><input value={when}onChange={e=>setWhen(e.target.value)}/><button onClick={save}>Save</button></div><Grid items={items.map(x=>({title:x.title,description:x.when_text,location:x.status}))}/></section>}
function Documents(){const[file,setFile]=useState(null);const[docs,setDocs]=useState([]);async function load(){setDocs(await api('/api/documents'))}useEffect(()=>{load()},[]);async function upload(){if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('doc_type','general');const r=await fetch(API+'/api/documents',{method:'POST',headers:authHeaders(),body:fd});if(!r.ok)alert('Upload failed');load()}return <section className="page"><h1>Document Vault</h1><div className="composer"><input type="file"onChange={e=>setFile(e.target.files[0])}/><button onClick={upload}><Upload/>Upload</button></div><Grid items={docs.map(d=>({title:d.filename,description:d.ai_summary,location:d.doc_type}))}/></section>}
function Profile({user,setUser}){return <section className="page"><h1>Profile</h1><div className="profileCard"><User/><h2>{user.first_name}</h2><p>{user.email}</p><p>{user.branch} Veteran • {user.city}, {user.state}</p></div></section>}
function Admin(){const[o,setO]=useState(null);const[users,setUsers]=useState([]);useEffect(()=>{api('/admin/overview').then(setO);api('/admin/users').then(setUsers)},[]);return <section className="page"><h1>Admin Dashboard</h1>{o&&<div className="stats">{Object.entries(o).map(([k,v])=><div><b>{v}</b><span>{k}</span></div>)}</div>}<h2>Users</h2><Grid items={users.map(u=>({title:`${u.first_name} — ${u.email}`,description:`${u.role} • ${u.branch}`,location:`${u.city}, ${u.state}`}))}/></section>}
function Grid({items=[]}){return <div className="grid">{items.map((x,i)=><div className="card"key={i}><h3>{x.title||x.name}</h3><p>{x.description||x.note||x.summary||''}</p><small>{x.location||x.type||x.when_text||''}</small>{(x.url||x.maps_url)&&<a target="_blank"href={x.url||x.maps_url}>Open</a>}</div>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
