import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bell, Calendar, Camera, CheckCircle2, FileText, Heart, Home, LogOut, MapPin, Medal, Mic, MicOff, Music, Play, Plus, Shield, Sparkles, User, Volume2} from 'lucide-react';
import './style.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
const branches = ['Army','Air Force','Navy','Marines','Coast Guard','Space Force'];
const defaultProfile = {name:'James', email:'james@example.com', branch:'Army', city:'Dallas', state:'TX', interests:['community','benefits','outdoors'], preferred_tone:'calm and positive'};

function api(path, opts={}){return fetch(`${API}${path}`, {headers:{'Content-Type':'application/json', ...(opts.headers||{})}, ...opts}).then(async r=>{if(!r.ok) throw new Error(await r.text()); return r.json()})}
function firstName(profile){return (profile?.name||'Veteran').split(' ')[0]}
function speak(text){try{window.speechSynthesis?.cancel(); const u=new SpeechSynthesisUtterance(text); u.rate=.95; u.pitch=1; window.speechSynthesis?.speak(u)}catch{}}
function playTone(){const ctx=new (window.AudioContext||window.webkitAudioContext)(); const o=ctx.createOscillator(); const g=ctx.createGain(); o.type='sine'; o.frequency.value=432; g.gain.value=.025; o.connect(g); g.connect(ctx.destination); o.start(); setTimeout(()=>{o.stop(); ctx.close()}, 6500)}

function App(){const [profile,setProfile]=useState(()=>JSON.parse(localStorage.getItem('vb_profile')||'null')); if(!profile) return <Login onLogin={setProfile}/>; return <Dashboard profile={profile} setProfile={setProfile}/>}

function Login({onLogin}){const [form,setForm]=useState(defaultProfile); function submit(e){e.preventDefault(); localStorage.setItem('vb_profile', JSON.stringify(form)); onLogin(form)} return <div className="loginPage"><div className="loginCard"><div className="brand"><Medal/><b>ValorBuddy</b></div><h1>Your AI companion for life after service.</h1><p>Personalized veteran support, voice assistance, memories, reminders, local activities, and practical benefits guidance.</p><form onSubmit={submit}><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="First name"/><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email"/><div className="row"><select value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}>{branches.map(b=><option key={b}>{b}</option>)}</select><input value={form.state} onChange={e=>setForm({...form,state:e.target.value})} placeholder="State"/></div><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="City"/><button>Enter ValorBuddy</button></form><small>Not medical care. For emergencies or immediate crisis, call 911 or 988 and press 1.</small></div></div>}

function Dashboard({profile,setProfile}){const [tab,setTab]=useState('home'); const [status,setStatus]=useState({}); const [reply,setReply]=useState(`Welcome back, ${firstName(profile)}. I’m ready when you are.`); const [events,setEvents]=useState([]); const [memories,setMemories]=useState([]); const [reminders,setReminders]=useState([]); const [toast,setToast]=useState('');
 useEffect(()=>{api('/health').then(setStatus).catch(()=>setStatus({status:'offline'})); loadAll()},[]);
 async function loadAll(){loadEvents(); api(`/memories?profile_email=${encodeURIComponent(profile.email)}`).then(setMemories).catch(()=>{}); api(`/reminders?profile_email=${encodeURIComponent(profile.email)}`).then(setReminders).catch(()=>{})}
 async function loadEvents(){const d=await fetch(`${API}/activities?city=${encodeURIComponent(profile.city)}&state=${encodeURIComponent(profile.state)}&interest=veteran activities`).then(r=>r.json()).catch(()=>({items:[]})); setEvents(d.items||[])}
 function logout(){localStorage.removeItem('vb_profile'); setProfile(null)}
 async function ask(message){setReply('Thinking...'); try{const memoryNotes=memories.slice(0,5).map(m=>`${m.title}: ${m.note}`); const data=await api('/ai/companion',{method:'POST', body:JSON.stringify({profile,message,recent_memories:memoryNotes})}); setReply(data.reply); speak(data.reply)}catch{const msg=`${firstName(profile)}, I had trouble reaching the AI service, but I’m still here. Try again in a moment.`; setReply(msg); speak(msg)}}
 async function addReminder(title, when_text){const row=await api('/reminders',{method:'POST',body:JSON.stringify({profile_email:profile.email,title,when_text})}); setReminders([row,...reminders]); setToast('Reminder saved.'); if(Notification?.permission==='granted') new Notification('ValorBuddy reminder saved',{body:title})}
 return <div className="app"><aside><div className="brand"><Medal/><b>ValorBuddy</b></div><nav>{[['home',Home,'Home'],['companion',Heart,'Companion'],['memories',Camera,'Memories'],['events',Calendar,'Events'],['music',Music,'Music'],['benefits',Shield,'Benefits'],['reminders',Bell,'Reminders']].map(([id,I,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={18}/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/> Logout</button></aside><main><header><div><p className="eyebrow">{profile.branch} veteran support</p><h1>Good to see you, {firstName(profile)}.</h1><p>Voice-first support for reminders, memories, local activities, benefits guidance, and positive companionship.</p></div><div className="profile"><User/> <span>{profile.name}<small>{profile.city}, {profile.state}</small></span></div></header>{toast&&<div className="toast">{toast}</div>}<div className="status"><span className={status.status==='ok'?'ready':'pending'}>API: {status.status||'checking'}</span><span className={status.gemini?'ready':'pending'}>Gemini: {status.gemini?'Ready':'Fallback'}</span><span className={status.google_maps?'ready':'pending'}>Local events: {status.google_maps?'Live':'Fallback'}</span></div>{tab==='home'&&<HomePanel profile={profile} reply={reply} ask={ask} events={events} memories={memories} reminders={reminders} addReminder={addReminder}/>} {tab==='companion'&&<Companion reply={reply} ask={ask}/>} {tab==='memories'&&<Memories profile={profile} memories={memories} setMemories={setMemories}/>} {tab==='events'&&<Events events={events} reload={loadEvents}/>} {tab==='music'&&<MusicPanel/>} {tab==='benefits'&&<Benefits ask={ask}/>} {tab==='reminders'&&<Reminders reminders={reminders} addReminder={addReminder}/>}</main></div>}

function VoiceBox({ask}){const [text,setText]=useState('Find veteran events near me this weekend.'); const [listening,setListening]=useState(false); const recRef=useRef(null); function mic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){alert('Speech recognition is not available in this browser. Use Chrome or the mobile app fallback text box.'); return} const rec=new SR(); rec.lang='en-US'; rec.interimResults=false; rec.onstart=()=>setListening(true); rec.onend=()=>setListening(false); rec.onerror=()=>setListening(false); rec.onresult=e=>{const t=e.results[0][0].transcript; setText(t); ask(t)}; recRef.current=rec; rec.start()} return <section className="voiceHero"><div><h2><Mic/> Voice Companion</h2><p>Tap the mic and speak naturally. ValorBuddy responds by name and reads the answer aloud.</p></div><textarea value={text} onChange={e=>setText(e.target.value)}/><div className="actions"><button onClick={mic}>{listening?<MicOff/>:<Mic/>}{listening?'Listening...':'Speak'}</button><button onClick={()=>ask(text)}><Sparkles/> Ask ValorBuddy</button></div></section>}
function HomePanel({profile,reply,ask,events,memories,reminders,addReminder}){return <><div className="grid two"><VoiceBox ask={ask}/><section className="card response"><h2>ValorBuddy says</h2><p>{reply}</p><button onClick={()=>speak(reply)}><Volume2/> Read again</button></section></div><div className="quick"><button onClick={()=>ask('I need a calm grounding check-in')}>Grounding check-in</button><button onClick={()=>ask('Find local veteran events near me')}>Find events</button><button onClick={()=>playTone()}><Play/> Play calm tone</button><button onClick={()=>addReminder('Check in with ValorBuddy','Tonight')}>Remind me tonight</button></div><div className="grid three"><Metric title="Saved memories" value={memories.length}/><Metric title="Local activities" value={events.length}/><Metric title="Active reminders" value={reminders.length}/></div><Events events={events.slice(0,3)}/></>}
function Companion({reply,ask}){return <div className="grid two"><VoiceBox ask={ask}/><section className="card"><h2>Positive companion mode</h2><p>{reply}</p><ul><li>Grounding and encouragement</li><li>Memory prompts and photo reflections</li><li>Reminders for appointments and routines</li><li>Veteran-friendly local activities</li></ul><p className="note">ValorBuddy is supportive technology, not clinical care. For crisis, call 988 and press 1.</p></section></div>}
function Memories({profile,memories,setMemories}){const [title,setTitle]=useState('My proud service memory'); const [note,setNote]=useState(''); async function add(){const row=await api('/memories',{method:'POST',body:JSON.stringify({profile_email:profile.email,title,note,tags:['positive']})}); setMemories([row,...memories]); setNote('')} return <section className="card"><h2><Camera/> Memory Wall</h2><p>Add positive memories, photos, family moments, milestones, and stories you want ValorBuddy to remember.</p><div className="form"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Memory title"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What should ValorBuddy remember?"/><button onClick={add}><Plus/> Save memory</button></div><div className="cards">{memories.map(m=><article key={m.id}><b>{m.title}</b><p>{m.note}</p><small>{new Date(m.created_at).toLocaleString()}</small></article>)}</div></section>}
function Events({events=[], reload}){return <section className="card"><h2><MapPin/> Veteran-friendly local activities</h2><p>Connect Google Places for live nearby activities. Fallback results are shown until API keys are configured.</p>{reload&&<button onClick={reload}>Refresh events</button>}<div className="cards">{events.map((e,i)=><article key={i}><b>{e.title}</b><p>{e.location}</p><small>{e.type||e.date||''} {e.rating?`· Rating ${e.rating}`:''}</small></article>)}</div></section>}
function MusicPanel(){const [playing,setPlaying]=useState(false); function calm(){setPlaying(true); playTone(); setTimeout(()=>setPlaying(false),6500)} return <section className="card"><h2><Music/> Music Companion</h2><p>Play a built-in calming tone or open licensed music services for songs and playlists.</p><div className="quick"><button onClick={calm}><Play/> {playing?'Playing calm tone':'Play calm tone'}</button><a className="button" href="https://open.spotify.com/search/uplifting%20veteran%20motivation%20playlist" target="_blank">Open Spotify</a><a className="button" href="https://www.youtube.com/results?search_query=calm+instrumental+grounding+playlist" target="_blank">Open YouTube</a></div></section>}
function Benefits({ask}){return <section className="card"><h2><Shield/> Benefits guidance</h2><p>Ask in plain English. ValorBuddy can explain steps, create a checklist, and point you to official VA or VSO resources.</p><div className="quick"><button onClick={()=>ask('Help me create a VA benefits checklist')}>Benefits checklist</button><button onClick={()=>ask('What documents should I gather for a VA claim?')}>Documents needed</button><button onClick={()=>ask('Find a veteran service officer near me')}>Find VSO</button></div></section>}
function Reminders({reminders,addReminder}){const [title,setTitle]=useState('Call VA office'); const [when,setWhen]=useState('Tomorrow morning'); return <section className="card"><h2><Bell/> Reminders</h2><div className="form row"><input value={title} onChange={e=>setTitle(e.target.value)}/><input value={when} onChange={e=>setWhen(e.target.value)}/><button onClick={()=>addReminder(title,when)}>Save</button></div><div className="cards">{reminders.map(r=><article key={r.id}><b>{r.title}</b><p>{r.when_text}</p><small>{r.status}</small></article>)}</div></section>}
function Metric({title,value}){return <section className="metric"><CheckCircle2/><span>{title}</span><b>{value}</b></section>}

createRoot(document.getElementById('root')).render(<App/>);
