import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{MessageCircle,MapPin,Folder,Calendar,Shield,Search,User,LogOut,Menu,Bell,Settings,ChevronRight,Medal,Star,FileText,Mail,Home as HomeIcon,Target,Activity,Mic,MicOff,Volume2,CheckCircle2,BookOpen,Users,Briefcase,HeartPulse,DollarSign,Clock,Plus,Trash2}from'lucide-react';
import'./style.css';
const API=import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
const nav=[['home','Dashboard',HomeIcon],['chat','AI Assistant',MessageCircle,'LIVE'],['activities','Activities',Calendar],['resources','Resources',BookOpen],['documents','Document Vault',Folder],['reminders','Reminders',Bell,'3'],['messages','Messages',Mail,'2'],['mission','Mission Tracker',Target],['community','Community',Users],['claims','Benefits & Claims',Shield],['profile','Profile',User],['settings','Settings',Settings]];
const serviceBranches={
  army:{label:'U.S. Army Veteran',short:'Army',motto:'Duty. Honor. Support.',command:'Mission Control',status:'Mission Ready',progress:'Mission Progress',greeting:'WELCOME BACK',theme:'army'},
  airforce:{label:'U.S. Air Force Veteran',short:'Air Force',motto:'Aim High. Fly. Fight. Support.',command:'Flight Operations',status:'Flight Ready',progress:'Flight Status',greeting:'WELCOME BACK',theme:'airforce'},
  navy:{label:'U.S. Navy Veteran',short:'Navy',motto:'Honor. Courage. Commitment.',command:'Fleet Command',status:'Underway',progress:'Fleet Readiness',greeting:'WELCOME ABOARD',theme:'navy'},
  marines:{label:'U.S. Marine Corps Veteran',short:'Marines',motto:'Semper Fidelis. Always Faithful.',command:'Command Post',status:'Semper Fi Ready',progress:'Operational Readiness',greeting:'WELCOME BACK',theme:'marines'},
  coastguard:{label:'U.S. Coast Guard Veteran',short:'Coast Guard',motto:'Semper Paratus. Always Ready.',command:'Rescue Operations',status:'On Watch',progress:'Response Readiness',greeting:'WELCOME ABOARD',theme:'coastguard'},
  spaceforce:{label:'U.S. Space Force Veteran',short:'Space Force',motto:'Semper Supra. Always Above.',command:'Orbital Command',status:'Systems Nominal',progress:'Orbital Readiness',greeting:'WELCOME BACK',theme:'spaceforce'}
};
const defaultUser={name:'James',email:'james@example.com',state:'Texas',city:'Dallas',serviceBranch:'army',branch:'U.S. Army Veteran',interests:['jobs','discounts','community']};
function App(){const[user,setUser]=useState(JSON.parse(localStorage.getItem('vb_user')||'null'));if(!user)return <Login setUser={setUser}/>;return <Dashboard user={user} setUser={setUser}/>} 
function Login({setUser}){const[n,setN]=useState('James');const[e,setE]=useState('james@example.com');const[svc,setSvc]=useState('army');const branch=serviceBranches[svc];function go(){const u={...defaultUser,name:n||'Veteran',email:e||'veteran@example.com',serviceBranch:svc,branch:branch.label};localStorage.setItem('vb_user',JSON.stringify(u));setUser(u)}return <div className={`login tactical-bg theme-${svc}`}><div className="loginPanel"><MilitaryLogo/><div><h1>ValorBuddy</h1><p>Your AI Veteran Assistant</p></div><h2>Mission Login</h2><p className="muted">Select your service branch. ValorBuddy will personalize the command center color scheme automatically.</p><label className="fieldLabel">Service Branch</label><select value={svc} onChange={x=>setSvc(x.target.value)}>{Object.entries(serviceBranches).map(([id,b])=><option key={id} value={id}>{b.label.replace(' Veteran','')}</option>)}</select><input value={n} onChange={x=>setN(x.target.value)} placeholder="First name"/><input value={e} onChange={x=>setE(x.target.value)} placeholder="Email"/><button onClick={go}>Enter {branch.short} {branch.command} <ChevronRight size={18}/></button><small>{branch.motto}</small></div></div>}
function Dashboard({user,setUser}){const[tab,setTab]=useState('home');const[brief,setBrief]=useState([]);const theme=user.serviceBranch||'army';function updateBranch(serviceBranch){const branch=serviceBranches[serviceBranch];const u={...user,serviceBranch,branch:branch.label};localStorage.setItem('vb_user',JSON.stringify(u));setUser(u)}function out(){localStorage.removeItem('vb_user');setUser(null)}function route(cmd){const c=cmd.toLowerCase();setBrief(b=>[`Voice command received: “${cmd}”`,...b].slice(0,4));if(c.includes('event')||c.includes('activities'))setTab('activities');else if(c.includes('document')||c.includes('vault'))setTab('documents');else if(c.includes('remind'))setTab('reminders');else if(c.includes('benefit')||c.includes('claim'))setTab('claims');else if(c.includes('resource'))setTab('resources');else if(c.includes('community')||c.includes('support group'))setTab('community');else if(c.includes('assistant')||c.includes('ask')||c.includes('chat'))setTab('chat');else setTab('home')}return <div className={`appShell tactical-bg theme-${theme}`}><aside><div className="sideBrand"><MilitaryLogo/><div><b>VALORBUDDY</b><span>YOUR AI VETERAN ASSISTANT</span><div className="stars"><Star size={13}/><Star size={13}/><Star size={13}/></div></div></div><div className="userBlock"><div className="avatar"><User size={28}/></div><div><strong>{user.name}</strong><p>{user.branch||'U.S. Veteran'}</p><small>ID: VB-{user.name?.slice(0,2).toUpperCase()||'VT'}-72AF-19</small></div><i className="online"/></div><nav>{nav.map(([id,t,I,badge])=><button key={id} className={tab==id?'active':''} onClick={()=>setTab(id)}><I size={19}/><span>{t}</span>{badge&&<em>{badge}</em>}</button>)}<button onClick={out}><LogOut size={19}/><span>Logout</span></button></nav><div className="commitment"><b>COMMITMENT</b><div><Star size={14}/><Star size={14}/><Star size={14}/></div><p>Supporting those who served. Always.</p></div></aside><main><TopBar user={user} onVoice={route} onBranchChange={updateBranch}/>{tab==='home'&&<Home user={user} onNavigate={setTab} brief={brief} onVoice={route}/>} {tab==='chat'&&<Chat user={user}/>} {tab==='activities'&&<Activities/>} {tab==='resources'&&<Resources/>} {tab==='documents'&&<Docs/>} {tab==='reminders'&&<Reminders/>}{tab==='mission'&&<Mission/>}{tab==='community'&&<Community/>}{tab==='claims'&&<Claims/>}{tab==='messages'&&<Placeholder title="Messages" text="Secure messages, status updates, and appointment notices will appear here."/>}{tab==='profile'&&<Profile user={user}/>} {tab==='settings'&&<SettingsPage user={user} onBranchChange={updateBranch}/>}</main></div>}
function BranchSwitcher({value,onChange}){return <div className="branchSwitch" title="Switch service branch color theme">{Object.entries(serviceBranches).map(([id,b])=><button key={id} className={value===id?'active':''} onClick={()=>onChange(id)}>{b.short}</button>)}</div>}
function TopBar({user,onVoice,onBranchChange}){const svc=user.serviceBranch||'army';const branch=serviceBranches[svc]||serviceBranches.army;return <header className="topbar"><div className="mission"><button className="iconBtn"><Menu/></button><div><span>{branch.short.toUpperCase()} {branch.command.toUpperCase()}</span><small>{branch.motto} <i></i></small></div></div><div className="classified">// UNCLASSIFIED //</div><div className="topActions"><BranchSwitcher value={svc} onChange={onBranchChange}/><button className="iconBtn"><Search/></button><button className="iconBtn"><Bell/></button><button className="iconBtn"><Shield/></button><button className="iconBtn"><Settings/></button><VoiceButton compact onCommand={onVoice}/><div className="profilePill"><User size={19}/>{user.name}<ChevronRight size={16}/></div></div></header>}
function Home({user,onNavigate,brief,onVoice}){const tiles=[['AI Assistant',MessageCircle,'Ask anything and get clear next steps.','CHAT NOW','chat'],['Find Activities',MapPin,'Discover veteran events and support groups.','BROWSE','activities'],['Document Vault',Folder,'Store and organize important docs.','OPEN VAULT','documents'],['Reminders',Bell,'Track appointments and deadlines.','VIEW ALL','reminders'],['Mission Tracker',Target,'Track goals and daily progress.','VIEW PROGRESS','mission']];return <div className="missionGrid"><section className="heroBanner"><div><h1>{serviceBranches[user.serviceBranch||'army'].greeting}, {user.name?.toUpperCase()}</h1><div className="serviceBadge">{serviceBranches[user.serviceBranch||'army'].label}</div><div className="rankLine"><span></span><Star size={18}/><span></span></div><p>ValorBuddy helps you navigate resources, track missions, organize documents, and stay on top of what matters most.</p></div><div className="soldierShade"><Medal size={110}/></div></section><VoiceCommandPanel onCommand={onVoice}/><div className="tileGrid">{tiles.map(([title,I,desc,cta,id])=><div className="missionCard" key={title}><div className="circle"><I size={34}/></div><h3>{title}</h3><p>{desc}</p><button onClick={()=>onNavigate(id)}>{cta}<ChevronRight size={16}/></button></div>)}</div><Glance/><MissionProgress/><QuickVoice onCommand={onVoice}/><RightRail brief={brief}/></div>}
function VoiceCommandPanel({onCommand}){return <section className="voicePanel"><div><h2><Volume2/> Voice Command</h2><p>Tap the mic and speak a mission command.</p><p className="try">Try: “Find veteran events near me”</p></div><VoiceButton onCommand={onCommand}/></section>}
function VoiceButton({onCommand,compact=false}){const[active,setActive]=useState(false);const[txt,setTxt]=useState('');const recRef=useRef(null);function speak(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setTxt('Voice not supported in this browser.');return}const rec=new SR();rec.lang='en-US';rec.interimResults=false;rec.onstart=()=>setActive(true);rec.onend=()=>setActive(false);rec.onerror=()=>{setTxt('Mic access needed.');setActive(false)};rec.onresult=e=>{const t=e.results[0][0].transcript;setTxt(t);onCommand?.(t)};recRef.current=rec;rec.start()}function stop(){recRef.current?.stop();setActive(false)}return <button className={compact?'voiceMini':'voiceBtn'} onClick={active?stop:speak}>{active?<MicOff/>:<Mic/>}{!compact&&<span>{active?'Listening...':'Tap to Speak'}</span>}{txt&&!compact&&<small>{txt}</small>}</button>}
function Glance(){return <section className="glance"><h3>AT A GLANCE</h3>{[[Bell,5,'Reminders','Due This Week'],[Folder,12,'Documents','In Your Vault'],[Calendar,8,'Activities','This Month'],[Mail,3,'Messages','Unread'],[Target,'75%','Mission Progress','Keep Going']].map(([I,n,t,s])=><div key={t}><I/><b>{n}</b><span>{t}</span><small>{s}</small></div>)}</section>}
function MissionProgress(){return <section className="progressPanel"><h2>SERVICE READINESS <span>Your goals. Your journey. We are with you.</span></h2><div className="progressCards">{[[HeartPulse,'Health & Fitness',75,'3 of 4 tasks completed'],[Briefcase,'Career Growth',60,'3 of 5 tasks completed'],[DollarSign,'Financial Stability',40,'2 of 5 tasks completed'],[Users,'Community & Connection',80,'4 of 5 tasks completed']].map(([I,t,p,d])=><div className="progressCard" key={t}><h3><I/>{t}<b>{p}%</b></h3><div className="bar"><i style={{width:p+'%'}}/></div><small>{d}</small></div>)}</div></section>}
function QuickVoice({onCommand}){return <section className="quickVoice"><h3>QUICK VOICE ACTIONS <span>Try these commands</span></h3>{['Find events near me','What benefits am I eligible for?','Remind me to call the VA tomorrow','Show my documents','Find a support group'].map(x=><button key={x} onClick={()=>onCommand(x)}><Mic size={18}/>{x}</button>)}</section>}
function RightRail({brief}){return <section className="rightRail"><Panel title="Today’s Briefing" icon={Calendar}><ul className="brief"><li><Bell/> You have 3 reminders</li><li><Mail/> 2 new messages</li><li><Star/> 1 upcoming event</li>{brief.map((b,i)=><li key={i}><CheckCircle2/>{b}</li>)}</ul></Panel><Panel title="Upcoming Events" icon={Calendar}><div className="event"><b>JUN 02</b><span>Veterans Coffee Meetup<br/><small>Dallas, TX</small></span></div><div className="event"><b>JUN 05</b><span>Career Workshop<br/><small>Virtual Event</small></span></div><div className="event"><b>JUN 10</b><span>VA Benefits Info Session<br/><small>Irving, TX</small></span></div></Panel><Panel title="Readiness Status" icon={Target}><dl><dt>System Status</dt><dd>OPERATIONAL</dd><dt>Branch Status</dt><dd>READY</dd><dt>Security Level</dt><dd>UNCLASSIFIED</dd></dl></Panel><Panel title="Review Checklist" icon={CheckCircle2}><ul className="stats"><li>Military UI <b>Ready</b></li><li>Voice command <b>Ready</b></li><li>Clickable modules <b>Ready</b></li><li>Local demo <b>Ready</b></li></ul></Panel></section>}
function Panel({title,icon:Icon,children}){return <div className="panel"><h3><Icon size={18}/>{title}</h3>{children}</div>}
function Chat({user}){const[m,setM]=useState('');const[items,setItems]=useState([{role:'bot',text:`Hi ${user.name}, ValorBuddy is online. What mission can I help with today?`}]);async function send(text=m){if(!text.trim())return;setM('');setItems(i=>[...i,{role:'me',text}]);try{const r=await fetch(API+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:user.name,message:text,state:user.state,interests:user.interests})});const d=await r.json();setItems(i=>[...i,{role:'bot',text:d.reply}])}catch{setItems(i=>[...i,{role:'bot',text:'Backend not connected yet. Please check the API connection and try again.'}])}}return <div className="card chat"><h2>AI Assistant</h2><div className="messages">{items.map((x,i)=><div key={i} className={x.role}>{x.text}</div>)}</div><VoiceButton onCommand={send}/><div className="composer"><input value={m} onChange={e=>setM(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about benefits, local events, documents..."/><button onClick={()=>send()}>Send</button></div></div>}
function Activities(){const[a,setA]=useState([]);useEffect(()=>{fetch(API+'/activities').then(r=>r.json()).then(setA).catch(()=>setA([]))},[]);return <List title="Local Veteran Activities" data={a} fallback={['Veterans Coffee Meetup','Career Workshop','VA Benefits Info Session','VFW Family BBQ']}/>}function Resources(){const[r,setR]=useState([]);useEffect(()=>{fetch(API+'/resources').then(r=>r.json()).then(setR).catch(()=>setR([]))},[]);return <List title="Veteran Resources" data={r} fallback={['VA Benefits','State Veterans Office','Education Benefits','Veteran Discounts']}/>}function List({title,data,fallback}){return <div><h2 className="pageTitle">{title}</h2><div className="cards">{(data.length?data:fallback.map(x=>({title:x,name:x,description:'Demo card: connect backend for live data.'}))).map((x,i)=><div className="card lift" key={i}><h3>{x.title||x.name}</h3><p>{x.description||`${x.type} • ${x.location} • ${x.date}`}</p><button>Open <ChevronRight size={16}/></button></div>)}</div></div>}
function Docs(){const[docs,setDocs]=useState(['DD214.pdf','VA Benefit Letter.pdf','Service Record.pdf']);const[file,setFile]=useState('');return <div className="card pageCard"><h2><FileText/> Document Vault</h2><p className="muted">Organize DD214, benefit letters, service records, education records, and personal admin files.</p><div className="composer"><input value={file} onChange={e=>setFile(e.target.value)} placeholder="Document name"/><button onClick={()=>{if(file){setDocs([file,...docs]);setFile('')}}}><Plus/> Add</button></div><div className="docList">{docs.map(d=><div key={d}><Folder/>{d}<button onClick={()=>setDocs(docs.filter(x=>x!==d))}><Trash2 size={16}/></button></div>)}</div></div>}
function Reminders(){const[items,setItems]=useState(['Call VSO Friday','Review benefits paperwork','Attend career workshop']);const[n,setN]=useState('');return <div className="card pageCard"><h2><Bell/> Reminders</h2><div className="composer"><input value={n} onChange={e=>setN(e.target.value)} placeholder="Example: Call the VA tomorrow"/><button onClick={()=>{if(n){setItems([n,...items]);setN('')}}}><Plus/> Save</button></div><div className="docList">{items.map(x=><div key={x}><Clock/>{x}<button onClick={()=>setItems(items.filter(i=>i!==x))}><Trash2 size={16}/></button></div>)}</div></div>}
function Mission(){return <div className="pageCard"><MissionProgress/><Glance/></div>}
function Community(){return <List title="Community & Support" fallback={['Local VFW Post','Veteran Mentor Circle','Family Resource Night','Peer Networking Meetup']} data={[]}/>}function Claims(){return <List title="Benefits & Claims" fallback={['Claim Status Tracker','Eligibility Guide','Education Benefits','Housing Support']} data={[]}/>}function Profile({user}){return <div className="card pageCard"><h2>Profile</h2><p><b>Name:</b> {user.name}</p><p><b>Branch:</b> {user.branch}</p><p><b>Location:</b> {user.city}, {user.state}</p></div>}
function SettingsPage({user,onBranchChange}){const svc=user.serviceBranch||'army';return <div className="card pageCard"><h2>Settings</h2><p className="muted">Change the service branch theme used across your ValorBuddy command center.</p><div className="settingsBranches">{Object.entries(serviceBranches).map(([id,b])=><button key={id} className={svc===id?'active':''} onClick={()=>onBranchChange(id)}><Shield/>{b.short}<small>{b.motto}</small></button>)}</div></div>}
function Placeholder({title,text}){return <div className="card pageCard"><h2>{title}</h2><p>{text}</p></div>}
function MilitaryLogo(){return <div className="milLogo"><Shield size={28}/><Star size={14}/></div>}
createRoot(document.getElementById('root')).render(<App/>);
